[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_movie_review = "G2QagUQXZRktxGae3diNtJhA592W93mBVk5Hy3Usnrqi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/aadhi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
